FROM mcr.microsoft.com/openjdk/jdk:21-ubuntu

LABEL authors="yogeshwar.vhatkar"

WORKDIR /app

COPY build/libs/trivydemo-0.0.1-SNAPSHOT.jar trivy-demo-gzgc.jar

EXPOSE 8080

# Read GC parameters from the environment
ENTRYPOINT ["java", "-jar", "trivy-demo-gzgc.jar"]
CMD ["${GC_PARAMS}"]
