name: 51 - Test Web Service Generational ZGC

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GCNAME: "gzgc"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Gather machine info
        run: |
          cat /proc/cpuinfo > cpuinfo.txt
          cat /proc/meminfo > meminfo.txt

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: |
          pwd
          chmod 755 ./gradlew
          ./gradlew build

      - name: Log in to GitHub Container Registry
        run: |
          echo "Log in to GitHub Container Registry"
          pwd
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set lowercase repository owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and run container
        run: |
          docker build --file Dockerfile-${{ env.GCNAME }} -t ghcr.io/${{ env.REPO_OWNER }}/trivy-demo-${{ env.GCNAME }}:latest .
          docker push ghcr.io/${{ env.REPO_OWNER }}/trivy-demo-${{ env.GCNAME }}:latest
          docker run --name trivy-demo-${{ env.GCNAME }} -d -p 8181:8080 ghcr.io/${{ env.REPO_OWNER }}/trivy-demo-${{ env.GCNAME }}:latest

      - name: Setup k6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: '0.51.0'  # Specify the k6 version you want to use

      - name: Run k6 tests
        uses: grafana/run-k6-action@v1
        with:
          path: |
            ./tests/health-test.js
            ./tests/greet-test.js
          flags: --out csv=${{ env.GCNAME }}-test-results.csv  # Save the results to a CSV file

      - name: Extract GC logs
        run: docker cp trivy-demo-${{ env.GCNAME }}:/app/gc.log ./gc.log

      - name: Check and rename generated files
        run: |
          pwd
          ls -ltra
          mv health-test-summary.json ${{ env.GCNAME }}-health-test-summary.json
          mv greet-test-summary.json ${{ env.GCNAME }}-greet-test-summary.json
          mv gc.log ${{ env.GCNAME }}-gc.log
          ls -ltra

      - name: Send GC log to GCEasy
        run: |
          curl -X POST "https://gceasy.io/analyzeGC?apiKey=${{ secrets.GCEASY_API_KEY }}" \
          -H "Content-Type: text/plain" \
          --data-binary @${{ env.GCNAME }}-gc.log > ${GITHUB_WORKSPACE}/${{ env.GCNAME }}-gc-analysis.json

      - name: Upload test and analysis results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GCNAME }}-results
          path: |
            cpuinfo.txt
            meminfo.txt
            ${{ env.GCNAME }}-test-results.csv
            ${{ env.GCNAME }}-health-test-summary.json
            ${{ env.GCNAME }}-greet-test-summary.json
            ${{ env.GCNAME }}-gc.log
            ${{ env.GCNAME }}-gc-analysis.json

      - name: Stop container
        run: |
          docker ps
          docker stop trivy-demo-${{ env.GCNAME }}
          docker container prune -f
          docker ps
